platform :ios, '9.0'

target ‘newcrea8social’ do
  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleSignIn'

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

# end

# # very important to have, unless you removed React dependencies for Libraries 
# # and you rely on Cocoapods to manage it
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
    
#     targets_to_ignore = %w(React yoga)
#     if targets_to_ignore.include? target.name
#       target.remove_from_project
# #    if target.name == "React"
# #      target.remove_from_project
#     end
#   end
# end

